-- Gold Nile Supabase schema - Final Clean Version
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique constraint profiles_auth_user_fk references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  role text not null default 'reader' check (role in ('owner', 'reader')),
  status text not null default 'allowed' check (status in ('allowed', 'blocked')),
  login_count integer not null default 0,
  last_login timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.bank_accounts (
  id bigint generated by default as identity primary key,
  bank text not null,
  account_no text not null,
  currency text not null,
  balance numeric not null default 0,
  purpose text not null default '',
  iban text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null,
  entry_type text not null,
  bank text not null,
  currency text not null,
  amount numeric not null default 0,
  description text not null default '',
  direction text not null check (direction in ('in', 'out')),
  created_at timestamptz not null default now()
);

create table if not exists public.transfers (
  id bigint generated by default as identity primary key,
  invoice_no text not null,
  transfer_date date not null,
  transfer_type text not null check (transfer_type in ('incoming_internal', 'incoming_external', 'outgoing_internal', 'outgoing_external')),
  direction text not null check (direction in ('in', 'out')),
  party text not null,
  amount numeric not null default 0,
  currency text not null,
  status text not null,
  purpose text not null,
  note text not null default '',
  document_path text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  department text not null,
  is_manager boolean not null default false,
  role text not null default '',
  phone text not null default '',
  status text not null default 'active',
  salary numeric not null default 0,
  currency text not null default 'USD',
  hire_date date,
  deductions numeric not null default 0,
  bonuses numeric not null default 0,
  commissions numeric not null default 0,
  warnings text not null default '',
  contracts text not null default '',
  achievements text not null default '',
  passport_number text not null default '',
  passport_path text not null default '',
  photo_path text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  department text not null,
  assignee text not null default '',
  status text not null default 'new',
  due date,
  priority text not null default 'medium',
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  storage_path text not null default '',
  mime_type text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.government_letters (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  storage_path text not null default '',
  mime_type text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('present', 'excused', 'absent')),
  note text not null default '',
  created_at timestamptz not null default now(),
  unique (employee_id, attendance_date)
);

alter table public.profiles enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.journal_entries enable row level security;
alter table public.transfers enable row level security;
alter table public.employees enable row level security;
alter table public.tasks enable row level security;
alter table public.documents enable row level security;
alter table public.government_letters enable row level security;
alter table public.attendance_logs enable row level security;

create or replace function public.is_owner()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where auth_user_id = auth.uid() and role = 'owner' and status = 'allowed') $$;

create or replace function public.is_allowed_reader()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where auth_user_id = auth.uid() and status = 'allowed') $$;

create policy profiles_owner_all on public.profiles for all to authenticated using (public.is_owner()) with check (public.is_owner());
create policy profiles_self_read on public.profiles for select to authenticated using (auth_user_id = auth.uid() and status = 'allowed');

create policy bank_reader_select on public.bank_accounts for select to authenticated using (public.is_allowed_reader());
create policy bank_owner_write on public.bank_accounts for all to authenticated using (public.is_owner()) with check (public.is_owner());
insert into public.profiles (auth_user_id, full_name, role, status)

