-- ============================================================
-- Gold Nile — Supabase Schema (v4 · Final)
-- آمن للتشغيل مرارًا. يحذف السياسات القديمة ويعيد إنشاءها.
-- ============================================================

create extension if not exists pgcrypto;

-- ============================================================
-- الجدول 1: profiles — مستخدمو النظام (للمصادقة والصلاحيات)
-- ============================================================
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  email text not null default '',
  full_name text not null default '',
  phone text not null default '',
  role text not null default 'reader' check (role in ('owner','reader')),
  status text not null default 'pending' check (status in ('pending','allowed','blocked')),
  avatar_url text not null default '',
  notes text not null default '',
  login_count integer not null default 0,
  last_login timestamptz,
  created_at timestamptz not null default now()
);

-- تأكيد وجود الأعمدة لو الجدول أُنشئ سابقًا بصيغة قديمة
alter table public.profiles add column if not exists email text not null default '';
alter table public.profiles add column if not exists avatar_url text not null default '';
alter table public.profiles add column if not exists notes text not null default '';

-- ============================================================
-- الجدول 2: dashboard_state — كل بيانات الموقع (JSON واحد)
-- ============================================================
create table if not exists public.dashboard_state (
  id integer primary key check (id = 1),
  data_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

-- ============================================================
-- الجدول 3: employees — مزامنة الموظفين (للتقارير الخارجية)
-- ============================================================
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  emp_code text not null default '',
  name text not null,
  department text not null default '',
  is_manager boolean not null default false,
  role text not null default '',
  nationality text not null default '',
  phone text not null default '',
  email text not null default '',
  status text not null default 'active',
  salary numeric not null default 0,
  allowances numeric not null default 0,
  currency text not null default 'SDG',
  hire_date date,
  end_date date,
  end_reason text not null default '',
  passport_number text not null default '',
  passport_path text not null default '',
  photo_path text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists employees_status_idx on public.employees(status);
create index if not exists employees_department_idx on public.employees(department);

-- ============================================================
-- تفعيل RLS على كل الجداول
-- ============================================================
alter table public.profiles enable row level security;
alter table public.dashboard_state enable row level security;
alter table public.employees enable row level security;

-- ============================================================
-- دوال الصلاحيات (SECURITY DEFINER لمنع الحلقات)
-- ============================================================
create or replace function public.is_owner()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where auth_user_id = auth.uid()
      and role = 'owner'
      and status = 'allowed'
  );
$$;

create or replace function public.is_allowed_reader()
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where auth_user_id = auth.uid()
      and status = 'allowed'
  );
$$;

-- ============================================================
-- سياسات profiles
-- ============================================================
drop policy if exists profiles_owner_all on public.profiles;
create policy profiles_owner_all on public.profiles
  for all to authenticated
  using (public.is_owner())
  with check (public.is_owner());

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
  for select to authenticated
  using (auth_user_id = auth.uid());

-- ============================================================
-- سياسات dashboard_state
-- ============================================================
drop policy if exists dashboard_state_select on public.dashboard_state;
drop policy if exists dashboard_state_insert on public.dashboard_state;
drop policy if exists dashboard_state_update on public.dashboard_state;
drop policy if exists dashboard_state_anon_select on public.dashboard_state;
drop policy if exists dashboard_state_anon_insert on public.dashboard_state;
drop policy if exists dashboard_state_anon_update on public.dashboard_state;

create policy dashboard_state_select on public.dashboard_state
  for select to authenticated
  using (public.is_allowed_reader());

create policy dashboard_state_insert on public.dashboard_state
  for insert to authenticated
  with check (id = 1 and public.is_owner());

create policy dashboard_state_update on public.dashboard_state
  for update to authenticated
  using (id = 1 and public.is_owner())
  with check (id = 1 and public.is_owner());

-- ============================================================
-- سياسات employees
-- ============================================================
drop policy if exists employees_reader_select on public.employees;
drop policy if exists employees_owner_write on public.employees;
drop policy if exists employees_anon_select on public.employees;
drop policy if exists employees_anon_insert on public.employees;
drop policy if exists employees_anon_update on public.employees;
drop policy if exists employees_anon_delete on public.employees;

create policy employees_reader_select on public.employees
  for select to authenticated
  using (public.is_allowed_reader());

create policy employees_owner_write on public.employees
  for all to authenticated
  using (public.is_owner())
  with check (public.is_owner());

-- ============================================================
-- المُشغّل: إنشاء profile تلقائيًا عند إضافة مستخدم جديد
-- ============================================================
create or replace function public.handle_new_goldnile_user()
returns trigger
language plpgsql security definer
set search_path = public
as $$
begin
  insert into public.profiles(auth_user_id, email, full_name, role, status)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    'reader',
    'pending'
  )
  on conflict (auth_user_id) do update set
    email = excluded.email,
    full_name = excluded.full_name;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_goldnile on auth.users;
create trigger on_auth_user_created_goldnile
after insert on auth.users
for each row execute function public.handle_new_goldnile_user();

-- ============================================================
-- إنشاء الصف الأساسي للداشبورد (فارغ)
-- ============================================================
insert into public.dashboard_state (id, data_json)
values (1, '{"public":{},"dashboard":{}}'::jsonb)
on conflict (id) do nothing;

-- ============================================================
-- تم بنجاح ✅
-- الخطوة التالية: أنشئ مستخدم الأدمن من Authentication
-- ============================================================